name: FTP Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTPD_SERVER }}
          username: ${{ secrets.FTPD_USERNAME }}
          password: ${{ secrets.FTPD_PASSWORD }}
          port: 21
          server-dir: /
          dangerous-clean-slate: false
